version: "3"

services:
  quizapp:
    container_name: lito-quizapp
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    command: -c shared_buffers=500MB -c fsync=off
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "pg_isready"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lito

networks:
  lito:


volumes:
  postgres_data:
    driver: local